# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
  workflow_dispatch:

name: check-version

permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: devel
          cran: https://CRAN.R-project.org

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::desc

      - name: Compare Package versions
         run: |
             pr <- desc::desc(file = "DESCRIPTION")
             pr_v <- pr$get_version()
             # TODO: Change git commit
             default <- desc::desc(file = "DESCRIPTION")
             default_v <- pr$get_version()
             stopifnot(default_v <= pr_v)
         shell: Rscript {0}            
